version: 2.0.{build}
image: Visual Studio 2017
configuration: Debug
cache: 
  - src\Coalesce.Web\node_modules     # local npm modules
  - '%APPDATA%\npm-cache'             # npm cache
  - '%LocalAppData%\NuGet\v3-cache'   # Nuget v3
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    dotnet restore

    cd src\Coalesce.Web

    npm install

    cd ..\..
build:
  parallel: true
  project: Coalesce.sln
  verbosity: minimal
after_build:
  - dotnet pack "src\IntelliTect.Coalesce\IntelliTect.Coalesce.csproj" -c %CONFIGURATION% --no-build --include-symbols --output "%APPVEYOR_BUILD_FOLDER%\artifacts"
  - dotnet pack "src\IntelliTect.Coalesce.CodeGeneration\IntelliTect.Coalesce.CodeGeneration.csproj" -c %CONFIGURATION% --no-build --include-symbols --output "%APPVEYOR_BUILD_FOLDER%\artifacts"
  - dotnet pack "src\IntelliTect.Coalesce.Cli\IntelliTect.Coalesce.Cli.csproj" -c %CONFIGURATION% --no-build --include-symbols --output "%APPVEYOR_BUILD_FOLDER%\artifacts"
  - dotnet pack "src\IntelliTect.Coalesce.DotnetCliTool\IntelliTect.Coalesce.DotnetCliTool.csproj" -c %CONFIGURATION% --no-build --include-symbols --output "%APPVEYOR_BUILD_FOLDER%\artifacts"
artifacts:
- path: artifacts\**\*.*
deploy:
  provider: NuGet
  server: https://ci.appveyor.com/nuget/intellitect-jamnmeof65y0/api/v2/package 
  symbol_server: https://ci.appveyor.com/nuget/intellitect-jamnmeof65y0/api/v2/package
  api_key:
    secure: 6BCd6W92HLY2RV4bTQSKNue9eoB7ETEYbvihtXy8T5k=
  skip_symbols: false
  artifact: /.*\.nupkg/
